on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
name: Publish Football-CRM App
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Copy env file
        run: 'echo "$ENV" > .env'
        shell: bash
        env:
          ENV: ${{secrets.ENV_PROD}}

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          dev: no
          args: --profile --ignore-platform-reqs

      - name: Use Node.js 16
        uses: actions/setup-node@v2-beta
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: subdir/package-lock.json

      - name: 🔨 Build Project
        run: |
          npm install
          npm run production

      - name: List output files
        run: ls -lah && ls -lah public

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{secrets.FTP_SERVER}}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          git-ftp-args: --insecure
