on: push
name: Publish Football-CRM App
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Copy env file
        run: echo ${{secrets.ENV_PROD}} >> .env

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          dev: no
          args: --profile --ignore-platform-reqs

      - name: Use Node.js 16
        uses: actions/setup-node@v2-beta
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: subdir/package-lock.json

      - name: 🔨 Build Project
        run: |
          npm install
          npm run production

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{secrets.FTP_SERVER}}
          port: ${{secrets.FTP_PORT}}
          server-dir: ${{secrets.FTP_SERVER_DIR}}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          exclude: '[**/.git*, **/.git*/**, **/node_modules/**, **/storage/**]'
